#!/bin/bash -l

# Set SCC project
#$ -P pathoscope

# Specify hard time limit for the job. 
#   The job will be aborted if it runs longer than this time.
#   The default time is 12 hours
#$ -l h_rt=100:00:00

# Send an email when the job finishes or if it is aborted (by default no email is sent).
#$ -m a

# Give job a name
#$ -N dbclark

# Request cores
#$ -pe omp 6

# Memory overall
#$ -l mem_total=150G

# Memory per core
#$ -l mem_per_core=11G

# Combine output and error files into a single file
#$ -j y

# Specify the output file name
#$ -o setup_clark.qlog

# Submit an array job with N tasks 
#$ -t 1

#   ask for scratch space
#$ -l scratch=100G

# Use SGE_TASK_ID env variable to select appropriate input file from bash array
# Bash array index starts from 0, so need to subtract one from SGE_TASK_ID value

# Keep track of information related to the current job
echo "=========================================================="
echo "Start date : $(date)"
echo "Job name : $JOB_NAME"
echo "Job ID : $SGE_TASK_ID"
echo "=========================================================="

module load clark/1.3.0.0

export OMP_NUM_THREAD=$NSLOTS
# SCC_CLARK_DIR -- Base Package Directory
# SCC_CLARK_BIN -- Package Executables Directory

bash ${SCC_CLARK_BIN}/set_targets.sh DIR_DB bacteria viruses fungi human
