---
output:
  html_document: default
  pdf_document: default
---

```{r}
suppressPackageStartupMessages(
  {
  library(taxonomizr)
  library(tidyverse)
  library(stringr)
  library(rentrez)
  library(geneviewer)
  }
)

```

## Metascope/Pathoscope

### Method 1 (use accession numbers)

```{r}
## zgrep '^>' bacteria.fasta.gz >> "metascope_bacteria_raw.txt"

bacteria <- "metascope/metascope_bacteria_raw.txt"
fungi <- "metascope/metascope_fungi_raw.txt"
viral <- "metascope/metascope_viral_raw.txt"

line_bacteria <- readLines(bacteria)
line_fungi <- readLines(fungi)
line_viral <- readLines(viral)

all_lines <- c(line_bacteria, line_fungi, line_viral)

```

```{r}
accession_numbers <- as.vector(str_extract(all_lines, "(?<=^>)[^ ]+"))

taxid <- taxonomizr::accessionToTaxa(accession_numbers, sqlFile = "../../../../taxonomizr_db/accessionTaxa.sql")
taxid_unique <- unique(taxid)

unique_genome_names <- apply(taxonomizr::getTaxonomy(taxid_unique, sqlFile = "../../../../taxonomizr_db/accessionTaxa.sql", desiredTaxa = c("genus", "species")), 1, function(x) paste0(x, collapse = ";"))
```

```{r}
length(unique_genome_names)
length(taxid_unique)
```

```{r}
sum(is.na(taxid))
```

### use batch entrez NCBI
```{r}
line_retry_taxid <- readLines("metascope/batch_process_na/results/metascope_na_NCBI.txt")
taxid_retry_unique <- unique(line_retry_taxid)

unique_genome_names_retry <- apply(taxonomizr::getTaxonomy(taxid_retry_unique, sqlFile = "../../../../taxonomizr_db/accessionTaxa.sql", desiredTaxa = c("genus", "species")), 1, function(x) paste0(x, collapse = ";"))
```

```{r}
length(unique_genome_names_retry)
length(taxid_retry_unique)
```

### total genomes for metascope
```{r}
total_genomes_metascope <- length(taxid_retry_unique) + length(taxid_unique)
total_genomes_metascope
```





### Method 2 (column extraction)

```{r}
split_words <- strsplit(all_lines, " ")
names <- sapply(split_words, function(x) paste(x[2], x[3]))
unique_names <- unique(names)
```

```{r}
length(unique_names)
```

## Kraken2/Bracken

```{r}
kraken <- "kracken_raw.txt"
line_kraken <- readLines(kraken)

split_kraken <- strsplit(line_kraken, split = "\t")



```

## Centrifuge

```{r}
centrifuge <- "centrifuge_raw.txt"
line_centrifuge <- readLines(centrifuge)
line_accession_centrifuge <- line_centrifuge[1:8243]
split_centrifuge <- strsplit(line_accession_centrifuge, split = " ")
centrifuge_accession <- sapply(split_centrifuge, function(x) x[[1]])

```

```{r}
taxid_centrifuge <- taxonomizr::accessionToTaxa(centrifuge_accession, sqlFile = "../../../../taxonomizr_db/accessionTaxa.sql")
```

```{r}
sum(is.na(taxid_centrifuge))
```

```{r}
na_position <- which(is.na(taxid_centrifuge))
na_accession_centrifuge <- centrifuge_accession[na_position]

na_line_centrifuge <- line_accession_centrifuge[na_position]
```
### use batch entrez NCBI
```{r}
write.table(na_accession_centrifuge, file = "centrifuge_na_accession.txt", row.names = FALSE, col.names = FALSE, quote = FALSE)
```

```{r}
gbk <- read_gbk("NCBI Batch Entrez/centrifuge_accession_output/section1.txt")
df <- gbk_features_to_df(gbk, feature = "source")
```


```{r}
result <- c()
for (i in seq_along(na_accession_centrifuge)) {
  current_accession <- na_accession_centrifuge[i]
  message("Processing ", current_accession, " (", i, " out of ", length(na_accession_centrifuge), " )")
  ncbi_id <- tryCatch(
    entrez_search(db = "nucleotide", term = current_accession)$ids, 
    error = function(e) 
      message(as.character(e$message), " for ", current_accession)
  )
  Sys.sleep(1)
  our_id <- entrez_link(dbfrom = "nuccore", id = ncbi_id, db = "all")$link$nuccore_nuccore_rsgb
  
  if (length(our_id) == 0 || is.null(our_id)) {
    message("No links found for ", current_accession)
    next
  }
  Sys.sleep(1)
  extract_taxid <- entrez_summary(db="nuccore", id=our_id) %>% extract_from_esummary("taxid")
  if (length(extract_taxid) == 0 || is.null(extract_taxid)) {
    message("No taxID found for ", current_accession)
    next
  } else {
    message("Found taxID for ", current_accession)
  }
  result <- c(result, extract_taxid)
  Sys.sleep(1)
}
```



```{r}
entrez_search(db="nucleotide", term="NC_005261.2") %>% str
```

```{r}
ncbi_id <- entrez_search(db="nuccore", term="NC_005261.2")$ids
```

```{r}
our_id <- entrez_link(dbfrom = "nuccore", id = ncbi_id, db="all")
entrez_summary(db="nuccore", id=our_id$links$nuccore_nuccore_rsgb) %>% str
```

```{r}
line_vec_accession_centrifuge <- line_centrifuge[14719:length(line_centrifuge)]
split_centrifuge_vec <- as.vector(str_extract(line_vec_accession_centrifuge, "(?<=\\|)[^|:]+(?=:)"))

```

```{r}
taxid_centrifuge_vec <- taxonomizr::accessionToTaxa(split_centrifuge_vec, sqlFile = "../../../../taxonomizr_db/accessionTaxa.sql")
```

```{r}
sum(is.na(taxid_centrifuge_vec))
```

```{r}
na_position_vec <- which(is.na(taxid_centrifuge_vec))
na_vec_accession_centrifuge <- split_centrifuge_vec[na_position_vec]
```
