#!/bin/bash -l

# Set SCC project
#$ -P pathoscope

# Specify hard time limit for the job. 
#   The job will be aborted if it runs longer than this time.
#   The default time is 12 hours
#$ -l h_rt=50:00:00

# Send an email when the job is aborted
#$ -m e

# Request cores
#$ -pe omp 8

# Give job a name
#$ -N runbrkn

# Specify the output file name
#$ -j y
#$ -o run_bracken_new_$TASK_ID.qlog

# Ask for scratch space
#$ -l scratch=100G

# Use the SGE_TASK_ID environment variable to select the appropriate input file from bash array
# Bash array index starts from 0, so we need to subtract one from SGE_TASK_ID value
#$ -t 1-24

# Keep track of information related to the current job
echo "=========================================================="
echo "Start date : $(date)"
echo "Job name : $JOB_NAME"
echo "Job ID : $SGE_TASK_ID"
echo "=========================================================="
start_time=$(date +%s)

# Define samples
stem=/restricted/projectnb/pathoscope/work/Yaoan/metagenomics_benchmarking/
# mapfile -t inputFastqFiles < ${stem}/MeSS_code/mess_manifest.txt
index=$(($SGE_TASK_ID-1))
# Create a flat array of ALL R1 files across all directories
baseDir="$stem"/MeSS_out_noerr/fastq
all_r1_files=($(find "$baseDir" -name "*_R1.fq.gz" | sort))
# Select the specific file for this task
readPath1="${all_r1_files[$index]}"
readPath2="${readPath1%_R1.fq.gz}_R2.fq.gz"
sampleName=$(basename "$readPath1" _R1.fq.gz)
# Get the sample type from the parent directory
sampleType=$(basename "$(dirname "$readPath1")")
# Strip "_noerr" suffix for matching priors_df files
sampleNameForPriors="${sampleName%_noerr}" 

# Obtain read files
ForwardRead=$readPath1
ReverseRead=$readPath2

# Load software
module load kraken2/2.1.2
inputDB=/restricted/projectnb/pathoscope/work/aubrey/newMB_02_25_meta_benchmark/db/StandardKrakenDB
outDir="${stem}/profilers/Bracken/outputs_new/${sampleType}"
mkdir -p "$outDir"
OUTREPORT="${outDir}/${sampleName}"

# Kraken-Classify a Sample AND Generate a Report File
# https://ccb.jhu.edu/software/bracken/index.shtml?t=manual

kraken2 --db $inputDB \
    --threads ${NSLOTS} \
    --report ${OUTREPORT}.kreport2 \
    --paired \
    --gzip-compressed $ForwardRead $ReverseRead \
    --output ${OUTREPORT}.out
    
rm -rf ${OUTREPORT}.out

# Step 3: Bracken [Abundance Estimation]

READ_LEN=150 # Dependent on database read_len param...
THRESHOLD=10 # Default
brkn_loc=${stem}/code/Bracken-2.9/bracken

${brkn_loc} -d ${inputDB} \
    -i ${OUTREPORT}.kreport2 \
    -o ${OUTREPORT}.bracken \
    -r ${READ_LEN} \
    -l 'S' \
    -t ${THRESHOLD}

echo DONE!

# Save timings
end_time=$(date +%s)
elapsed_time=$((end_time - start_time))
echo "Execution Time: ${elapsed_time} seconds" >> ${stem}/profilers/Bracken/timings/${sampleName}_timing.txt
