#!/bin/bash -l

# Set SCC project
#$ -P pathoscope

# Specify hard time limit for the job. 
#   The job will be aborted if it runs longer than this time.
#   The default time is 12 hours
#$ -l h_rt=100:00:00

# Send an email when the job finishes or if it is aborted (by default no email is sent).
#$ -m a

# Give job a name
#$ -N centrifuge

# Request cores
#$ -pe omp 8

# Memory overall
#$ -l mem_total=150G

# Memory per core
#$ -l mem_per_core=11G

# Combine output and error files into a single file
#$ -j y

# Specify the output file name
#$ -o run_centrifuge_new_$TASK_ID.qlog

# Submit an array job with N tasks 
#$ -t 1-24

# ask for scratch space
#$ -l scratch=100G

# Use SGE_TASK_ID env variable to select appropriate input file from bash array
# Bash array index starts from 0, so need to subtract one from SGE_TASK_ID value

# Keep track of information related to the current job
echo "=========================================================="
echo "Start date : $(date)"
echo "Job name : $JOB_NAME"
echo "Job ID : $SGE_TASK_ID"
echo "=========================================================="
start_time=$(date +%s)
NTHREADS=8

# Define samples
stem=/restricted/projectnb/pathoscope/work/Yaoan/metagenomics_benchmarking/
# mapfile -t inputFastqFiles < ${stem}/MeSS_code/mess_manifest.txt
index=$(($SGE_TASK_ID-1))
# Create a flat array of ALL R1 files across all directories
baseDir="$stem"/MeSS_out_noerr/fastq
all_r1_files=($(find "$baseDir" -name "*_R1.fq.gz" | sort))
# Select the specific file for this task
readPath1="${all_r1_files[$index]}"
readPath2="${readPath1%_R1.fq.gz}_R2.fq.gz"
sampleName=$(basename "$readPath1" _R1.fq.gz)
# Get the sample type from the parent directory
sampleType=$(basename "$(dirname "$readPath1")")
# Strip "_noerr" suffix for matching priors_df files
sampleNameForPriors="${sampleName%_noerr}" 

# Path to Centrifuge files
CENTRIFUGE_HOME=${stem}/code/centrifuge-1.0.4.2
db_loc="/restricted/projectnb/pathoscope/work/aubrey/newMB_02_25_meta_benchmark/db/centrifuge/p_compressed+h+v"
export PATH=$CENTRIFUGE_HOME:$PATH

# Dir to save output files
outDir="${stem}/profilers/Centrifuge/outputs_noerr/${sampleType}"
mkdir -p "$outDir"

# Run centrifuge

$CENTRIFUGE_HOME/centrifuge -x $db_loc \
    -k 18 \
    --seed 55 \
    -1 $readPath1 \
    -2 $readPath2 \
    -p $NTHREADS \
    --report-file ${outDir}/${sampleName}_summary.tsv \
    -S ${outDir}/${sampleName}_report.txt
    
end_time=$(date +%s)
elapsed_time=$((end_time - start_time))
echo "Execution Time: ${elapsed_time} seconds" >> ${outDir}/${sampleName}_timing.txt
