#!/bin/bash -l


SGE_TASK_ID="$1"
NSLOTS="$2"

nproc --all

# Define samples
stem=/restricted/projectnb/pathoscope/work/Yaoan/metagenomics_benchmarking/
# mapfile -t inputFastqFiles < ${stem}/MeSS_code/mess_manifest.txt
index=$(($SGE_TASK_ID-1))
# Create a flat array of ALL R1 files across all directories
baseDir="$stem"/MeSS_out_noerr/fastq
all_r1_files=($(find "$baseDir" -name "*_R1.fq.gz" | sort))
# Select the specific file for this task
readPath1="${all_r1_files[$index]}"
readPath2="${readPath1%_R1.fq.gz}_R2.fq.gz"
sampleName=$(basename "$readPath1" _R1.fq.gz)
# Get the sample type from the parent directory
sampleType=$(basename "$(dirname "$readPath1")")
# Strip "_noerr" suffix for matching priors_df files
sampleNameForPriors="${sampleName%_noerr}" 
echo $sampleType
echo $sampleName

# Path to Centrifuge files
CENTRIFUGE_HOME=${stem}/code/centrifuge-1.0.4.2
db_loc="/restricted/projectnb/pathoscope/work/aubrey/newMB_02_25_meta_benchmark/db/centrifuge/p_compressed+h+v"
export PATH=$CENTRIFUGE_HOME:$PATH

# Dir to save output files
outDir="${stem}/profilers/Centrifuge/outputs_new_timing/${sampleType}"
mkdir -p "$outDir"

# Run centrifuge

$CENTRIFUGE_HOME/centrifuge -x $db_loc \
    -k 18 \
    --seed 55 \
    -1 $readPath1 \
    -2 $readPath2 \
    -p $NSLOTS \
    --report-file ${outDir}/${sampleName}_summary.tsv \
    -S ${outDir}/${sampleName}_report.txt

echo "Done"
