#!/bin/bash -l

SGE_TASK_ID="$1"
NSLOTS="$2"

nproc --all

module load miniconda
module load bwa
source ~/.bashrc
conda activate /restricted/projectnb/pathoscope/work/Yaoan/metagenomics_benchmarking/my_conda_env
cd /restricted/projectnb/pathoscope/work/Yaoan/metagenomics_benchmarking/my_conda_env

stem=/restricted/projectnb/pathoscope/work/Yaoan/metagenomics_benchmarking
index=$(($SGE_TASK_ID-1))
# Create a flat array of ALL R1 files across all directories
baseDir="$stem"/MeSS_out/fastq
all_r1_files=($(find "$baseDir" -name "*_R1.fq.gz" | sort))

# Select the specific file for this task
readPath1="${all_r1_files[$index]}"
readPath2="${readPath1%_R1.fq.gz}_R2.fq.gz"
sampleName=$(basename "$readPath1" _R1.fq.gz)

# Get the sample type from the parent directory
sampleType=$(basename "$(dirname "$readPath1")")


echo "Task ID: $SGE_TASK_ID"
echo "Sample Name: $sampleName"
echo "Sample Type: $sampleType"
echo "R1 Read Path: $readPath1"
echo "R2 Read Path: $readPath2"

# Dir to save output files
outDir="${stem}/profilers/mOTUs/output_timing/${sampleType}"
mkdir -p "$outDir"



motus profile -f ${readPath1} -r ${readPath2} -n ${sampleName} -t $NSLOTS -o ${outDir}/${sampleName}.motus

echo "done"
