#!/bin/bash -l

SGE_TASK_ID="$1"
NSLOTS="$2"

nproc --all


stem=/restricted/projectnb/pathoscope/work/Yaoan/metagenomics_benchmarking
index=$(($SGE_TASK_ID-1))

# Create a flat array of ALL R1 files across all directories
baseDir="$stem"/MeSS_out_noerr/fastq
all_r1_files=($(find "$baseDir" -name "*_R1.fq.gz" | sort))

# Select the specific file for this task
readPath1="${all_r1_files[$index]}"
readPath2="${readPath1%_R1.fq.gz}_R2.fq.gz"
sampleName=$(basename "$readPath1" _R1.fq.gz)

# Get the sample type from the parent directory
sampleType=$(basename "$(dirname "$readPath1")")

echo "Task ID: $SGE_TASK_ID"
echo "Data Directory: $dataDir"
echo "Sample Name: $sampleName"
echo "Sample Type: $sampleType"
echo "R1 Read Path: $readPath1"
echo "R2 Read Path: $readPath2"

### MAKE WORKING DIR
workingDir="${sampleType}_${sampleName}_tmp"
rm -rf $TMPDIR/$workingDir
mkdir $TMPDIR/$workingDir

# Set filepaths; indices
pathoscope="/restricted/projectnb/pathoscope/code/PathoScope/pathoscope/pathoscope2.py"
indDir="/restricted/projectnb/pathoscope/reflib/2020_index_bowtie"
targLibs="bacteria,viral,fungi"
filterLibs="human_mouse,phix174"
outDir="${stem}/profilers/PathoScope2/outputs_new/${sampleType}"
mkdir -p "$outDir"

# Run Pathoscope
module load bowtie2
module load python2/2.7.16

$pathoscope MAP \
    -1 $readPath1 \
    -2 $readPath2 \
    -indexDir $indDir \
    -targetIndexPrefixes $targLibs \
    -filterIndexPrefixes $filterLibs \
    -expTag $sampleName \
    -outDir ${TMPDIR}/${workingDir} \
    -numThreads $NSLOTS

$pathoscope ID \
    -expTag $sampleName \
    -alignFile ${TMPDIR}/${workingDir}/outalign.sam \
    --noUpdatedAlignFile \
    -outDir $outDir

# Remove working directory
rm -rf $TMPDIR/$workingDir

