#!/bin/bash -l

# Set SCC project
#$ -P pathoscope

# Specify cpu architecture and type
#$ -l cpu_arch=haswell
#$ -l cpu_type=E5-2660v3

# Specify hard time limit for the job. 
#   The job will be aborted if it runs longer than this time.
#   The default time is 12 hours
#$ -l h_rt=50:00:00


# Send an email when the job is aborted
#$ -m a

# Request cores
#$ -pe omp 4

# Give job a name
#$ -N pathoscope_new_timing

# Specify the output file name
#$ -j y
#$ -o run_pathoscope2_new_test_timing_$TASK_ID.qlog

# Ask for scratch space
#$ -l scratch=500G

# Use the SGE_TASK_ID environment variable to select the appropriate input file from bash array
# Bash array index starts from 0, so we need to subtract one from SGE_TASK_ID value
#$ -t 1-48
echo $HOSTNAME
chmod +755 /restricted/projectnb/pathoscope/work/Yaoan/metagenomics_benchmarking/profilers/PathoScope2/run_pathoscope2.qsub
time /restricted/projectnb/pathoscope/work/Yaoan/metagenomics_benchmarking/profilers/PathoScope2/run_pathoscope2.qsub ${SGE_TASK_ID} ${NSLOTS}