#!/bin/bash -l

# Set SCC project
#$ -P pathoscope

# Specify hard time limit for the job. 
#   The job will be aborted if it runs longer than this time.
#   The default time is 12 hours
#$ -l h_rt=50:00:00

# Send an email when the job finishes or if it is aborted (by default no email is sent).
#$ -m a

# Give job a name
#$ -N m_blast_new

# Request cores
#$ -pe omp 8

# Memory overall
$ -l mem_total=150G

# Memory per core
#$ -l mem_per_core=16G

# Combine output and error files into a single file
#$ -j y

# Specify the output file name
#$ -o run_metascope_b_new_$TASK_ID.qlog

# Submit an array job with N tasks 
#$ -t 1-24

#   ask for scratch space
#$ -l scratch=100G

# Use SGE_TASK_ID env variable to select appropriate input file from bash array
# Bash array index starts from 0, so need to subtract one from SGE_TASK_ID value

# Keep track of information related to the current job
echo "=========================================================="
echo "Start date : $(date)"
echo "Job name : $JOB_NAME"
echo "Job ID : $SGE_TASK_ID"
echo "=========================================================="
start_time=$(date +%s)

stem=/restricted/projectnb/pathoscope/work/Yaoan/metagenomics_benchmarking
# mapfile -t inputFastqFiles < ${stem}/MeSS_code/mess_manifest.txt
index=$(($SGE_TASK_ID-1))

# Create a flat array of ALL R1 files across all directories
baseDir="$stem"/MeSS_out_noerr/fastq
all_r1_files=($(find "$baseDir" -name "*_R1.fq.gz" | sort))

# Select the specific file for this task
readPath1="${all_r1_files[$index]}"
readPath2="${readPath1%_R1.fq.gz}_R2.fq.gz"

sampleName=$(basename "$readPath1" _R1.fq.gz)
# Get the sample type from the parent directory
sampleType=$(basename "$(dirname "$readPath1")")

# Strip "_noerr" suffix for matching priors_df files
sampleNameForPriors="${sampleName%_noerr}"


echo "Task ID: $SGE_TASK_ID"
echo "Data Directory: $dataDir"
echo "Sample Name: $sampleName"
echo "Sample Type: $sampleType"
echo "R1 Read Path: $readPath1"
echo "R2 Read Path: $readPath2"

### MAKE WORKING DIR
workingDir="${sampleName}_tmp"
rm -rf $TMPDIR/$workingDir
mkdir $TMPDIR/$workingDir

### Run MetaScope
stem_profiler=${stem}/profilers/MetaScope_blast
indexDir="/restricted/projectnb/pathoscope/reflib/2020_index_bowtie/"
expTag=$sampleName
outDir="${stem_profiler}/outputs_new/${sampleType}"
mkdir -p "$outDir"
tmpDir="$TMPDIR/$workingDir/"

### NEW parameters for MetaScope 1.7.3
taxDB=/restricted/projectnb/pathoscope/data/blastdb/2024_accession_taxa/accessionTaxa.sql

### Choose filter and targets to use
target="bacteria,fungi,viral"
filter="human_mouse,phix174"

## Select which priors_df
priors_df_path=${stem_profiler}/priors_df
priors_df=${priors_df_path}/${sampleNameForPriors}.csv

# BLAST db
blast_db="/restricted/projectnb/pathoscope/data/blastdb/nt/nt"

# Run MetaScope
module load samtools
module load R/4.4.3
module load blast blast+

export R_LIBS_USER="/restricted/projectnb/pathoscope/work/Yaoan/R"

Rscript --vanilla --max-ppsize=500000 ${stem_profiler}/run_metascope_b.R \
${readPath1} ${readPath2} ${indexDir} ${expTag} ${outDir} ${tmpDir} ${NSLOTS} \
${target} ${filter} \
${taxDB} ${priors_df} ${blast_db}

rm -rf $TMPDIR/$workingDir

end_time=$(date +%s)
elapsed_time=$((end_time - start_time))
echo "Execution Time: ${elapsed_time} seconds" >> ${outDir}/${sampleName}_timing.txt
