#!/bin/bash -l


SGE_TASK_ID="$1"
NSLOTS="$2"

nproc --all

stem=/restricted/projectnb/pathoscope/work/Yaoan/metagenomics_benchmarking
# mapfile -t inputFastqFiles < ${stem}/MeSS_code/mess_manifest.txt
index=$(($SGE_TASK_ID-1))

# Create a flat array of ALL R1 files across all directories
baseDir="$stem"/MeSS_out_noerr/fastq
all_r1_files=($(find "$baseDir" -name "*_R1.fq.gz" | sort))

# Select the specific file for this task
readPath1="${all_r1_files[$index]}"
readPath2="${readPath1%_R1.fq.gz}_R2.fq.gz"

sampleName=$(basename "$readPath1" _R1.fq.gz)
# Get the sample type from the parent directory
sampleType=$(basename "$(dirname "$readPath1")")

# Strip "_noerr" suffix for matching priors_df files
sampleNameForPriors="${sampleName%_*err}"


echo "Task ID: $SGE_TASK_ID"
echo "Data Directory: $dataDir"
echo "Sample Name: $sampleName"
echo "Sample Type: $sampleType"
echo "R1 Read Path: $readPath1"
echo "R2 Read Path: $readPath2"

### MAKE WORKING DIR
workingDir="${sampleType}_tmp"
rm -rf $TMPDIR/$workingDir
mkdir $TMPDIR/$workingDir

### Run MetaScope
stem_profiler=${stem}/profilers/MetaScope_blast
indexDir="/restricted/projectnb/pathoscope/reflib/2025_index_bowtie/"
expTag=$sampleName
outDir="${stem_profiler}/outputs_new_all_timing/${sampleType}/${sampleName}"
mkdir -p "$outDir"
tmpDir="$TMPDIR/$workingDir/"

### NEW parameters for MetaScope 1.7.3
taxDB=/restricted/projectnb/pathoscope/data/blastdb/2024_accession_taxa/accessionTaxa.sql

### Choose filter and targets to use
target="target_reference_2"
filter="filter_reference"

## Select which priors_df
priors_df_path=${stem_profiler}/priors_df
priors_df=${priors_df_path}/${sampleNameForPriors}.csv

# BLAST db
blast_db="/restricted/projectnb/pathoscope/data/blastdb/nt/nt"

# Run MetaScope
module load samtools
module load R/4.4.3
module load blast blast+

export R_LIBS_USER="/restricted/projectnb/pathoscope/work/Yaoan/R"

Rscript --vanilla --max-ppsize=500000 ${stem_profiler}/run_metascope_b.R \
${readPath1} ${readPath2} ${indexDir} ${expTag} ${outDir} ${tmpDir} ${NSLOTS} \
${target} ${filter} \
${taxDB} ${priors_df} ${blast_db}

rm -rf $TMPDIR/$workingDir

