#!/bin/bash -l

# Set SCC project
#$ -P pathoscope

# Specify hard time limit for the job. 
#   The job will be aborted if it runs longer than this time.
#   The default time is 12 hours
#$ -l h_rt=200:00:00

# Send an email when the job finishes or if it is aborted (by default no email is sent).
#$ -m a

# Give job a name
#$ -N noerr_to_fastq

# Request cores
#$ -pe omp 16

# Memory overall
#$ -l mem_total=150G

# Memory per core
#$ -l mem_per_core=11G

# Combine output and error files into a single file
#$ -j y

# Submit an array job with N tasks 
# #$ -t 1-2

#   ask for scratch space
#$ -l scratch=100G

# Specify the output file name
#$ -o run_noerr_to_fastq.qlog


# Use SGE_TASK_ID env variable to select appropriate input file from bash array
# Bash array index starts from 0, so need to subtract one from SGE_TASK_ID value

# Keep track of information related to the current job
echo "=========================================================="
echo "Start date : $(date)"
echo "Job name : $JOB_NAME"
echo "Job ID : $SGE_TASK_ID"
echo "=========================================================="

stem=/restricted/projectnb/pathoscope/work/aubrey/newMB_02_25_meta_benchmark
wd=/restricted/projectnb/pathoscope/work/Yaoan/metagenomics_benchmarking
output_location=${wd}/MeSS/fastq
all_bam_files=/restricted/projectnb/pathoscope/work/aubrey/newMB_02_25_meta_benchmark/MeSS/out_samples/mess_sample_*_noerr/bam/error-free/*.bam

# create output dir if not existing
mkdir -p ${output_location}

# load samtools
module load samtools

# Process each path
for bam_file in ${all_bam_files}; do
    ## Process individual BAM file
    # Extract the sample size (100k, 1mil, or 10mil) from the path
    sample_size=$(echo ${bam_file} | sed 's/.*mess_sample_\([^_]*\)_noerr.*/\1/')
    
    # Extract just the filename without path and extension
    base_name=$(basename ${bam_file} .bam)
    
    # Create output filename with sample size prefix
    mkdir -p ${output_location}/${sample_size}
    output_fastq="${output_location}/${sample_size}/${base_name}_noerr"
    
    # Convert BAM to FASTQ
    echo "Converting ${bam_file} to ${output_fastq}"
    # samtools bam2fq ${bam_file} > ${output_fastq}
    samtools fastq \
    -1 "${output_fastq}_R1.fq.gz" \
    -2 "${output_fastq}_R2.fq.gz" \
    ${bam_file};
done
echo "DONE!"

module purge
